spring.application.name=shipment-tracking

spring.datasource.url=jdbc:postgresql://localhost:5432/shipment_tracking
spring.datasource.username=postgres
spring.datasource.password=Nandini@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
